[package]
name = "speaker_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-serial = "5"
midly = "0.5"
clap = { version = "4", features = ["derive"] }
